##### ****************************** CREATE ******************************

### STUDENTS
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
  "email": "johndoe@gmail.com",
  "name": "John Doe",
  "username": "john",
  "password": "scscsc",
  "courseCode":"9991"
}

### TEACHERS
POST http://localhost:8080/academics/api/teachers
Content-Type: application/json

{
  "email": "rolando_F@gmail.com",
  "name": "Rolando Ferreira",
  "username": "rolandoF",
  "password": "12Rk6_s",
  "office": "D.S.1.5"
}

### ADMINISTRATOR
POST http://localhost:8080/academics/api/administrators
Content-Type: application/json

{
  "email": "nicolasG@gmail.com",
  "name": "Nicolas Gonçales",
  "username": "nicolasGonc",
  "password": "kf623Fsb"
}

### COURSES
POST http://localhost:8080/academics/api/courses
Content-Type: application/json

{
  "code":"1234",
  "name": "Micro-Biology"
}

### SUBJECTS
POST http://localhost:8080/academics/api/subjects
Content-Type: application/json

{
  "code":"6",
  "name": "IA",
  "courseCode":"9991",
  "courseYear":"2",
  "scholarYear":"2021"
}

##### ****************************** UPDATE ******************************

### STUDENTS
PUT http://localhost:8080/academics/api/students/claire
Content-Type: application/json

{
  "courseCode": 1222
}

### COURSES
PUT http://localhost:8080/academics/api/courses/1234
Content-Type: application/json

{
  "name": "Biology"
}


### SUBJECTS
PUT http://localhost:8080/academics/api/subjects/1
Content-Type: application/json

{
  "courseCode":"1222"
}

### TEACHERS
PUT http://localhost:8080/academics/api/teachers/rolandoF
Content-Type: application/json

{
  "email": "rolandoFerreira@gmail.com",
  "password": "59_dhdF2",
  "office": "D.S.2.5"
}


### ADMINISTRATORS
PUT http://localhost:8080/academics/api/administrators/nicolasGonc
Content-Type: application/json

{
  "email": "nicolas_Goncalves@gmail.com",
  "name": "Nicolas Domingos Gonçales",
  "password": "fkfj43_d$"
}

##### ****************************** READ ******************************

##### STUDENTS
GET http://localhost:8080/academics/api/students

##### COURSES
GET http://localhost:8080/academics/api/courses

### ADMINISTRATORS
GET http://localhost:8080/academics/api/administrators

### SUBJECTS
GET http://localhost:8080/academics/api/subjects

### TEACHERS
GET http://localhost:8080/academics/api/teachers


##### ****************************** FIND ******************************

##### STUDENTS
GET http://localhost:8080/academics/api/students/john

##### COURSES
GET http://localhost:8080/academics/api/courses/9991/subjects

### ADMINISTRATORS
GET http://localhost:8080/academics/api/administrators/adminFabio

### SUBJECTS
GET http://localhost:8080/academics/api/subjects/3

### TEACHERS
GET http://localhost:8080/academics/api/teachers/teacherBruna/subjects

##### ****************************** DELETE ******************************

##### STUDENTS
DELETE http://localhost:8080/academics/api/students/carlaSoffia

##### COURSES
DELETE http://localhost:8080/academics/api/courses/9991

### ADMINISTRATORS
DELETE http://localhost:8080/academics/api/administrators/nicolasGonc

### SUBJECTS
DELETE http://localhost:8080/academics/api/subjects/1

### TEACHERS
DELETE http://localhost:8080/academics/api/teachers/teacherJoao


##### ****************************** STUDENT SUBJECTS ******************************

### STUDENTS
GET http://localhost:8080/academics/api/students/carlaSoffia/subjects

### STUDENTS
POST http://localhost:8080/academics/api/students/carlaSoffia/unroll/5

### STUDENTS
POST http://localhost:8080/academics/api/students/carlaSoffia/unroll/6


### STUDENTS
POST http://localhost:8080/academics/api/students/carlaSoffia/enroll/5


##### ****************************** SUBJECT STUDENTS ******************************

### SUBJECTS
GET http://localhost:8080/academics/api/subjects/2/students


##### ****************************** SUBJECT TEACHERS ******************************

### SUBJECTS
GET http://localhost:8080/academics/api/subjects/2/teachers

##### ****************************** TEACHER SUBJECTS ******************************

### Teachers
GET http://localhost:8080/academics/api/teachers/teacherBruna/subjects

##### ****************************** TEACHERS ASSOCIATE SUBJECT ******************************

### TEACHERS
POST http://localhost:8080/academics/api/teachers/teacherJoao/associate/2

### TEACHERS
POST http://localhost:8080/academics/api/teachers/teacherBruna/associate/3

### TEACHERS
POST http://localhost:8080/academics/api/teachers/teacherJoao/associate/4

### TEACHERS
POST http://localhost:8080/academics/api/teachers/teacherBruna/associate/1

### TEACHERS
POST http://localhost:8080/academics/api/teachers/teacherBruna/associate/2


##### ****************************** TEACHERS DISSOCIATE SUBJECT ******************************

### Teachers
POST http://localhost:8080/academics/api/teachers/teacherBruna/dissociate/1

### Teachers
POST http://localhost:8080/academics/api/teachers/teacherJoao/dissociate/4


