##### Students
GET http://localhost:8080/academics/api/students
Accept: application/json
###
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
 "email": "johndoe@mail.com",
 "name": "John Doe",
 "username": "john",
 "password": "jd",
 "courseCode":"9991"
}

### Students
DELETE http://localhost:8080/academics/api/students/john


### Students
PUT http://localhost:8080/academics/api/students/john
Content-Type: application/json

{
  "password": "1234",
  "email": "johndoe_12345@gmail.com",
  "courseCode": 3332
}

##### Courses
GET http://localhost:8080/academics/api/courses
Accept: application/json


### Courses
POST http://localhost:8080/academics/api/courses
Content-Type: application/json

{
  "code":"1234",
  "name": "Micro-Biology"
}

### Courses
PUT http://localhost:8080/academics/api/courses/1234
Content-Type: application/json

{
  "name": "Biology"
}


### Courses
DELETE http://localhost:8080/academics/api/courses/3332



### Courses
GET http://localhost:8080/academics/api/courses/3332



### Students
GET http://localhost:8080/academics/api/students/carlaSoffia/subjects

### Students
GET http://localhost:8080/academics/api/students/carlaSoffia


### Subjects
GET http://localhost:8080/academics/api/subjects/1/students

### Students
POST http://localhost:8080/academics/api/students/carlaSoffia/unroll/2

### Students
POST http://localhost:8080/academics/api/students/carlaSoffia/enroll/5

### Teachers
POST http://localhost:8080/academics/api/teachers/teacherJoao/associate/2

### Teachers
POST http://localhost:8080/academics/api/teachers/teacherJoao/associate/3

### Teachers
POST http://localhost:8080/academics/api/teachers/teacherJoao/associate/4

### Teachers
POST http://localhost:8080/academics/api/teachers/teacherBruna/associate/1

### Teachers
POST http://localhost:8080/academics/api/teachers/teacherBruna/associate/2

### Teachers
POST http://localhost:8080/academics/api/teachers/teacherJoao/dissociate/2

### Teachers
GET http://localhost:8080/academics/api/teachers/teacherJoao/subjects

### Subject
GET http://localhost:8080/academics/api/subjects/2/teachers